#:import Animation kivy.animation.Animation
#:import MDProgressBar kivymd.progressbar.MDProgressBar
#:import MDSlider kivymd.slider.MDSlider

#V0.2.1

AnchorLayout:
    ScreenManager:  # Define the Screens
        id: sm
        PerformanceScreen:
            name: "performance"
        MultiGaugeScreen:
            name: "multigauge"
        CarInfoScreen:
            name: "carinfo"
        CoolantScreen:
            name: "coolant"
        RPMScreen:
            name: "rpm"
        MenuScreen:
            name: "menu"
        RGBScreen:
            name: "RGB"

    AnchorLayout:  # Define the QuickKeys Area
        FloatLayout:
            size_hint: 1, 1
            Image:
                id: dock
                source: 'data/elements/dock.png'
                opacity: 1
                center_x: self.center_x
                center_y: self.center_y
                pos: 0, 0
                allow_stretch: True
                opacity: 0

            Button:
                id: dock_multigauge
                height: 80
                width: 80
                pos: -80, 400
                size_hint: None, None
                on_press:
                    sm.current = 'multigauge'
                    sm.transition.direction = 'up'
                    app.save()
                    app.OBDOFF()
                    app.OBDEnabler("CoolantTemp",1)
                    app.OBDEnabler("IntakeTemp",1)
                    app.OBDEnabler("ThrottlePos",1)
                background_normal: 'data/icons/multi_icon.png'
                background_down: 'data/icons/multi_icon_pressed.png'

                on_press: Animation(x=-80, duration=.2).start(dock_coolanttemp)
                on_press: Animation(x=-80, duration=.2).start(dock_performance)
                on_press: Animation(x=-80, duration=.2).start(dock_carinfo)
                on_press: Animation(x=-80, duration=.2).start(dock_RGB)
                on_press: Animation(x=-80, duration=.2).start(dock_multigauge)

            Button:
                id: dock_performance
                height: 80
                width: 80
                pos: -80, 320
                size_hint: None, None
                on_press:
                    sm.current = 'performance'
                    sm.transition.direction = 'up'
                    app.save()
                    app.OBDOFF()
                    app.OBDEnabler("CoolantTemp",1)
                    app.OBDEnabler("IntakeTemp",1)
                    app.OBDEnabler("LTFT",1)
                    app.OBDEnabler("STFT",1)
                    app.OBDEnabler("TimingAdv",1)
                    app.OBDEnabler("CatTemp",1)
                background_normal: 'data/icons/rpm_icon.png'
                background_down: 'data/icons/rpm_icon_pressed.png'

                on_press: Animation(x=-80, duration=.2).start(dock_coolanttemp)
                on_press: Animation(x=-80, duration=.2).start(dock_performance)
                on_press: Animation(x=-80, duration=.2).start(dock_carinfo)
                on_press: Animation(x=-80, duration=.2).start(dock_RGB)
                on_press: Animation(x=-80, duration=.2).start(dock_multigauge)

            Button:
                id: dock_carinfo
                height: 80
                width: 80
                pos: -80, 240
                size_hint: None, None
                on_press:
                    sm.current = 'carinfo'
                    sm.transition.direction = 'up'
                    app.save()
                    app.OBDOFF()
                    app.OBDEnabler("RunTime",1)
                    app.OBDEnabler("FuelLevel",1)
                    app.OBDEnabler("WarmUpsSinceDTC",1)
                    app.OBDEnabler("DistanceSinceDTC",1)
                background_normal: 'data/icons/carinfo_icon.png'
                background_down: 'data/icons/carinfo_icon_pressed.png'

            Button:
                id: dock_coolanttemp
                height: 80
                width: 80
                pos: -80, 160
                size_hint: None, None
                on_press:
                    sm.current = 'coolant'
                    sm.transition.direction = 'up'
                    app.save()
                    app.OBDOFF()
                    app.OBDEnabler("CoolantTemp",1)
                background_normal: 'data/icons/coolanttemp_icon.png'
                background_down: 'data/icons/coolanttemp_icon_pressed.png'

            Button:
                id: dock_RGB
                height: 80
                width: 80
                pos: -80, 80
                size_hint: None, None
                on_press:
                    sm.current = 'RGB'
                    sm.transition.direction = 'up'
                    app.save()
                background_normal: 'data/icons/theme_icon.png'
                background_down: 'data/icons/theme_icon_pressed.png'

            Button:
                id: dock_home
                height: 80
                width: 80
                pos: 0, 0
                size_hint: None, None
                on_press:
                    sm.current = 'menu'
                    sm.transition.direction = 'up'
                    app.save()
                background_normal: 'data/icons/home.png'
                background_down: 'data/icons/home_pressed.png'
                on_press: Animation(x=0, duration=.2).start(dock_coolanttemp)
                on_press: Animation(x=0, duration=.2).start(dock_performance)
                on_press: Animation(x=0, duration=.2).start(dock_carinfo)
                on_press: Animation(x=0, duration=.2).start(dock_RGB)
                on_press: Animation(x=0, duration=.2).start(dock_multigauge)

            Image:
                id: shutdown
                source: 'data/wallpapers/shutdown.png'
                opacity: 1 if app.shutdownflag == 1 else 0
                center_x: self.center_x
                center_y: self.center_y
                pos: 0, 0
                allow_stretch: True

<MultiGaugeScreen>:
    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/MultiGaugeScreen.png"

        Label: #Label to display Coolant Temp
            markup: True
            text: (str(app.CoolantTemp)) + u'\N{DEGREE SIGN}'
            font_size: 40
            pos: -210, 210
        Label: #Label to display Intake Temp
            markup: True
            text: (str(app.IntakeTemp)) + u'\N{DEGREE SIGN}'
            font_size: 40
            pos: 5, 210
        Label: #Label to display Throttle Pos
            markup: True
            text: (str(app.ThrottlePos)) + "%"
            font_size: 40
            pos: 220, 210

        Image:
            source: ('data/icons/coolanttemp_cold_icon.png' if app.CoolantTemp < 170 else ('data/icons/coolanttemp_hot_icon.png' if app.CoolantTemp > 210 else 'data/icons/coolanttemp_icon.png')) #white normally, red if overheating, blue if cold
            size: 80, 80
            pos: -215, -207

        Image:
            source: ('data/icons/intaketemp_hot_icon.png' if app.IntakeTemp > 110 else 'data/icons/intaketemp_icon.png') #white normally, red if hot air
            size: 80, 80
            pos: 0, -210

        Image:
            source: 'data/icons/throttlepos_icon.png'
            size: 80, 80
            pos: 215, -207

        Button:
            id: BrightButton
            text: "Make it bright"
            height: 480
            width: 720
            size_hint: None, None
            pos: 80, 0
            on_press: app.BrightnessSet(220)
            on_press: Animation(x=850, duration=.1).start(BrightButton)
            on_press: Animation(x=80, duration=.1).start(DimButton)
            opacity: 0

        Button:
            id: DimButton
            text: "Make it dim"
            height: 480
            width: 720
            size_hint: None, None
            pos: 850, 0
            on_press: app.BrightnessSet(15)
            on_press: Animation(x=80, duration=.1).start(BrightButton)
            on_press: Animation(x=850, duration=.1).start(DimButton)
            opacity: 0


    FloatLayout:
        size_hint: 1, 0.72916666666666666666666666666667
        VerticalMultiGaugeCoolantProgressBar: #Coolant Temp Bar
            pos: -215, 65
            value: app.CoolantTemp_ForBar
            orientation: "vertical"
            max: 80
            opacity: .5

        VerticalMultiGaugeIntakeTempThrottleProgressBar: #Intake Temp Bar
            pos: 0, 65
            value: app.IntakeTemp
            orientation: "vertical"
            max: 140
            opacity: .5

        VerticalMultiGaugeIntakeTempThrottleProgressBar: #Throttle Pos
            pos: 215, 65
            value: app.ThrottlePos
            orientation: "vertical"
            max: 100
            opacity: .5

<CarInfoScreen>:
    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/CarInfoScreen.png"
        Label:
            text: "Current Cycle Minutes:"
            text_size: self.size
            halign: 'left'
            font_size: 25
            pos: 400, 342
        Label:
            text: "Cycles Since Reset:"
            text_size: self.size
            halign: 'left'
            font_size: 25
            pos: 400, 262
        Label:
            text: "Miles Since Reset:"
            text_size: self.size
            halign: 'left'
            font_size: 25
            pos: 400, 182
        Label:
            text: "Gallons Remaining:"
            text_size: self.size
            halign: 'left'
            font_size: 25
            pos: 400, 102

        Image:
            source: 'data/icons/CarInfoIcons/timer.png'
            size: 80, 80
            pos: -50, 120
        Image:
            source: 'data/icons/CarInfoIcons/counter.png'
            size: 80, 80
            pos: -50, 40
        Image:
            source: 'data/icons/CarInfoIcons/distance.png'
            size: 80, 80
            pos: -50, -40
        Image:
            source: 'data/icons/CarInfoIcons/gas.png'
            size: 80, 80
            pos: -50, -120

        Label:
            text: (str(app.RunTime))
            text_size: self.size
            halign: 'left'
            font_size: 35
            pos: 680, 336
        Label:
            text: (str(app.WarmUpsSinceDTC))
            text_size: self.size
            halign: 'left'
            font_size: 35
            pos: 680, 256
        Label:
            text: (str(app.DistanceSinceDTC/1.60934)).strip()[:-9]
            text_size: self.size
            halign: 'left'
            font_size: 35
            pos: 680, 176
        Label:
            text: (str(app.FuelLevel*13.2/100)).strip()[:-1]
            text_size: self.size
            halign: 'left'
            font_size: 35
            pos: 680, 96

        Label:
            text: "Fuel"
            font_size: 25
            pos: -216, -190
        Label:
            markup: True
            text: (str(app.FuelLevel))  + "%"
            font_size: 30
            pos: -216, -150 + (app.FuelLevel*3.5)

    FloatLayout:
        size_hint: 1, 0.72916666666666666666666666666667 #350 tall
        VerticalMultiGaugeIntakeTempThrottleProgressBar:
            pos: -216, 65
            value: app.FuelLevel
            orientation: "vertical"
            max: 100
            opacity: .5

<PerformanceScreen>:
    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/black.png"
        Label:
            markup: True
            text: (str(app.CoolantTemp)) + u'\N{DEGREE SIGN}'
            font_size: 60
            pos: -250, 190
        Label:
            markup: True
            text: (str(app.IntakeTemp)) + u'\N{DEGREE SIGN}'
            font_size: 60
            pos: -250, -10
        Label:
            markup: True
            text: (str(app.STFT)) + "%"
            font_size: 60
            pos: 0, 190
        Label:
            markup: True
            text: (str(app.LTFT)) + "%"
            font_size: 60
            pos: 0, -10
        Label:
            markup: True
            text: (str(app.TimingAdv)) + u'\N{DEGREE SIGN}'
            font_size: 60
            pos: 260, 190
        Label:
            markup: True
            text: (str(app.CatTemp)) + u'\N{DEGREE SIGN}'
            font_size: 60
            pos: 260, -10


    FloatLayout:
        size_hint: .25, 1
        CoolantBar:
            pos: 50, 132
            value: app.CoolantTemp_ForBar
            orientation: "horizontal"
            max: 80
    FloatLayout:
        size_hint: .25, 1
        IntakeBar:
            pos: 50, -68
            value: app.IntakeTemp
            orientation: "horizontal"
            max: 150
    FloatLayout:
        size_hint: .125, 1
        STFuelTrimNegBar:
            pos: 300, 132
            value: app.STFT*-1
            orientation: "horizontal"
            reversed: True
            max: 25
    FloatLayout:
        size_hint: .125, 1
        STFuelTrimPosBar:
            pos: 400, 132
            value: app.STFT
            orientation: "horizontal"
            max: 25
    FloatLayout:
        size_hint: .125, 1
        LTFuelTrimNegBar:
            pos: 300, -68
            value: app.LTFT*-1
            orientation: "horizontal"
            reversed: True
            max: 25
    FloatLayout:
        size_hint: .125, 1
        LTFuelTrimPosBar:
            pos: 400, -68
            value: app.LTFT
            orientation: "horizontal"
            max: 25
    FloatLayout:
        size_hint: .125, 1
        TimingNegBar:
            pos: 550, 132
            value: app.TimingAdv*-1
            orientation: "horizontal"
            reversed: True
            max: 50
    FloatLayout:
        size_hint: .125, 1
        TimingPosBar:
            pos: 650, 132
            value: app.TimingAdv
            orientation: "horizontal"
            max: 50
    FloatLayout:
        size_hint: .25, 1
        CatTempBar:
            pos: 550, -68
            value: app.CatTemp
            orientation: "horizontal"
            max: 2000

    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/SmallGauge.png"
        Button:
            id: BrightButton
            text: "Make it bright"
            height: 480
            width: 720
            size_hint: None, None
            pos: 80, 0
            on_press: app.BrightnessSet(220)
            on_press: Animation(x=850, duration=.1).start(BrightButton)
            on_press: Animation(x=80, duration=.1).start(DimButton)
            opacity: 0

        Button:
            id: DimButton
            text: "Make it dim"
            height: 480
            width: 720
            size_hint: None, None
            pos: 850, 0
            on_press: app.BrightnessSet(15)
            on_press: Animation(x=80, duration=.1).start(BrightButton)
            on_press: Animation(x=850, duration=.1).start(DimButton)
            opacity: 0

<CoolantScreen>:
    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/CoolantScreen.png"
        Label:
            text: "Coolant Temp"
            opacity: .5
            font_size: 30
            pos: 230, 150

        Label: #Label to display Coolant Temp
            markup: True
            text: (str(app.CoolantTemp)) + u'\N{DEGREE SIGN}'
            font_size: 100
            pos: 240, 0

<RPMScreen>:
    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/TachScreen.png"
        Image:
            source: ('data/elements/VTEC.png' if app.RPM < 5000 else 'data/elements/VTEC_YO.png')

        Label: #Label to display RPM
            markup: True
            text: (str(app.RPM))
            font_size: 100
            pos: 40, -40
        Label: #Label to display vehicle max RPM
            markup: True
            text: (str(app.RPM_max))
            font_size: 35
            pos: 40, -200
        Button:
            text: "Reset Max"
            size_hint: None, None
            size: 140, 50
            pos: 110, 20
            on_press: app.zero_out_max()
            opacity: .25
    FloatLayout:
        size_hint: .8, 1
        EightKTachBar:
            pos: 120, 130
            value: app.RPM
            orientation: "horizontal"
            min: 0
            max: 8000

<RGBScreen>:
    FloatLayout: #Mode Buttons
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/black.png"
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 400, 260
            background_normal: 'data/icons/RGB/RGB_Coolant.png'
            background_down: 'data/icons/RGB/RGB_Coolant_pressed.png'
            on_press: app.Set_RGB_Mode("Coolant")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 400, 180
            background_normal: 'data/icons/RGB/RGB_RPM.png'
            background_down: 'data/icons/RGB/RGB_RPM_pressed.png'
            on_press: app.Set_RGB_Mode("RPM")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 400, 100
            background_normal: 'data/icons/RGB/RGB_Accel.png'
            background_down: 'data/icons/RGB/RGB_Accel_pressed.png'
            on_press: app.Set_RGB_Mode("Accelerometer")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 400, 20
            background_normal: 'data/icons/RGB/RGB_Off.png'
            background_down: 'data/icons/RGB/RGB_Off_pressed.png'
            on_press: app.Set_RGB_All(100,100,100,100,100,100)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()

    FloatLayout: #RGB presets
        size_hint: 1, 1
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 80, 390
            background_normal: 'data/icons/RGB/RGB_Red.png'
            background_down: 'data/icons/RGB/RGB_Red_pressed.png'
            on_press: app.Set_RGB_All(0,100,100,0,100,100)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 160, 390
            background_normal: 'data/icons/RGB/RGB_Green.png'
            background_down: 'data/icons/RGB/RGB_Green_pressed.png'
            on_press: app.Set_RGB_All(100,0,100,100,0,100)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 240, 390
            background_normal: 'data/icons/RGB/RGB_Blue.png'
            background_down: 'data/icons/RGB/RGB_Blue_pressed.png'
            on_press: app.Set_RGB_All(100,100,0,100,100,0)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 320, 390
            background_normal: 'data/icons/RGB/RGB_White.png'
            background_down: 'data/icons/RGB/RGB_White_pressed.png'
            on_press: app.Set_RGB_All(0,0,0,0,0,0)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 400, 390
            background_normal: 'data/icons/RGB/RGB_Purple.png'
            background_down: 'data/icons/RGB/RGB_Purple_pressed.png'
            on_press: app.Set_RGB_All(0,100,0,0,100,0)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 480, 390
            background_normal: 'data/icons/RGB/RGB_Teal.png'
            background_down: 'data/icons/RGB/RGB_Teal_pressed.png'
            on_press: app.Set_RGB_All(100,0,0,100,0,0)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 560, 390
            background_normal: 'data/icons/RGB/RGB_Orange.png'
            background_down: 'data/icons/RGB/RGB_Orange_pressed.png'
            on_press: app.Set_RGB_All(0,80,100,0,80,100)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 640, 390
            background_normal: 'data/icons/RGB/RGB_Yellow.png'
            background_down: 'data/icons/RGB/RGB_Yellow_pressed.png'
            on_press: app.Set_RGB_All(0,0,100,0,0,100)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()
        Button:
            height: 80
            width: 80
            size_hint: None, None
            pos: 720, 390
            background_normal: 'data/icons/RGB/RGB_GreenBlue.png'
            background_down: 'data/icons/RGB/RGB_GreenBlue_pressed.png'
            on_press: app.Set_RGB_All(100,0,100,100,100,0)
            on_press: app.Set_RGB_Mode("Normal")
            on_release: app.save()

    FloatLayout:
        size_hint: .1, .8
        MDSliderRed:
            pos: 100, 0
            orientation:'vertical'
            min:100
            max:0
            value: app.RGBSlider_R_DR_value
            on_value: app.RGBSlider_Color_Side(self.value, "R", "DR")
    FloatLayout:
        size_hint: .1, .8
        MDSliderGreen:
            pos: 200, 0
            orientation:'vertical'
            min:100
            max:0
            value: app.RGBSlider_G_DR_value
            on_value: app.RGBSlider_Color_Side(self.value, "G", "DR")
    FloatLayout:
        size_hint: .1, .8
        MDSliderBlue:
            pos: 300, 0
            orientation:'vertical'
            min:100
            max:0
            value: app.RGBSlider_B_DR_value
            on_value: app.RGBSlider_Color_Side(self.value, "B", "DR")

    FloatLayout:
        size_hint: .1, .8
        MDSliderRed:
            pos: 500, 0
            orientation:'vertical'
            min:100
            max:0
            value: app.RGBSlider_R_AS_value
            on_value: app.RGBSlider_Color_Side(self.value, "R", "AS")
    FloatLayout:
        size_hint: .1, .8
        MDSliderGreen:
            pos: 600, 0
            orientation:'vertical'
            min:100
            max:0
            value: app.RGBSlider_G_AS_value
            on_value: app.RGBSlider_Color_Side(self.value, "G", "AS")
    FloatLayout:
        size_hint: .1, .8
        MDSliderBlue:
            pos: 700, 0
            orientation:'vertical'
            min:100
            max:0
            value: app.RGBSlider_B_AS_value
            on_value: app.RGBSlider_Color_Side(self.value, "B", "AS")

<MenuScreen>:
    FloatLayout: #Main Elements
        size_hint: 1, 1
        Image:
            source: "data/wallpapers/blackgradient.png"
        Button:
            id: dock_power
            height: 80
            width: 80
            pos: 688, 20
            size_hint: None, None
            on_press: app.save()
            on_press: app.ScreenOnOff("OFF")
            on_release: app.shutdown()
            background_normal: 'data/icons/power.png'
            background_down: 'data/icons/power.png'

        Button:
            id: dock_reset
            height: 80
            width: 80
            pos: 688, 120
            size_hint: None, None
            on_press: app.save()
            on_release: app.reboot()
            background_normal: 'data/icons/reset.png'
            background_down: 'data/icons/reset.png'

        Button:
            id: dock_kill
            height: 80
            width: 80
            pos: 688, 220
            size_hint: None, None
            on_press: app.save()
            on_release: app.killapp()
            background_normal: 'data/icons/kill.png'
            background_down: 'data/icons/kill.png'


    FloatLayout:                                 #Brightnessbar buttons
        id: brightnessbarbuttons
        orientation: 'horizontal'
        size_hint: 1, 1 #define percentage of screen for brightness bar buttons

        Button: #Brightness 1
            id: brightness_1_button
            size_hint: .125, .2
            pos: 170, 392
            background_color:(0.9, 0.9, 0.9, 0.0)
            on_press: app.BrightnessSet(15)
            Image:
                source: 'data/icons/brightness1.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                size: 60, 60
                allow_stretch: True

        Button: #Brightness 2
            id: brightness_2_button
            size_hint: .125, .2
            pos: 260, 390
            background_color:(0.9, 0.9, 0.9, 0.0)
            on_press: app.BrightnessSet(60)
            Image:
                source: 'data/icons/brightness2.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                size: 60, 60
                allow_stretch: True

        Button: #Brightness 3
            id: brightness_3_button
            size_hint: .125, .2
            pos: 350, 390
            background_color:(0.9, 0.9, 0.9, 0.0)
            on_press: app.BrightnessSet(80)
            Image:
                source: 'data/icons/brightness3.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                size: 60, 60
                allow_stretch: True

        Button: #Brightness 4
            id: brightness_4_button
            size_hint: .125, .2
            pos: 440, 390
            background_color:(0.9, 0.9, 0.9, 0.0)
            on_press: app.BrightnessSet(120)
            Image:
                source: 'data/icons/brightness4.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                size: 60, 60
                allow_stretch: True

        Button: #Brightness 5
            id: brightness_5_button
            size_hint: .125, .2
            pos: 530, 390
            background_color:(0.9, 0.9, 0.9, 0.0)
            on_press: app.BrightnessSet(220)
            Image:
                source: 'data/icons/brightness5.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                size: 60, 60
                allow_stretch: True